base_model: runwayml/stable-diffusion-v1-5

train_images: data/comic_style/images
caption_file: data/comic_style/captions.txt   # optional
output_dir: runs/comic_lora

resolution: 512
max_train_steps: 1000
batch_size: 1
gradient_accumulation: 2
learning_rate: 8.0e-5
mixed_precision: fp16
lr_scheduler: cosine_with_restarts
save_every_steps: 250

lora_rank: 16
lora_alpha: 16
lora_target_modules: ["to_q","to_k","to_v","to_out.0","ff.net.0.proj","ff.net.2"]

prompt_prefix: "klarer Comic-Stil, saubere Outlines, kräftige Farben, minimal shading"
negative_prompt: "realistic photo, photorealistic, text watermark, abstract pattern"
seed: 123
