base_model: stabilityai/stable-diffusion-xl-base-1.0
output_dir: models/loras/real_style
train_images: data/real_style/images
resolution: 1024
caption_file: data/real_style/captions.txt      # optional
max_train_steps: 800
lr: 8.0e-5
batch_size: 1
lora_rank: 16
lora_alpha: 16
lora_target_modules: ["to_q","to_k","to_v","to_out.0","ff.net.0.proj","ff.net.2"]
prompt_prefix: "natural light, candid, shallow depth of field, instagram photo"
negative_prompt: "cartoon, illustration, painting, overprocessed, watermark"
seed: 123
